spring.application.name=server
# Conexiunea la baza de date
spring.datasource.url=jdbc:postgresql://localhost:5433/student_review
spring.datasource.username=user
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurare JPA/Hibernate
# "update" inseamna ca Spring va incerca sa creeze/actualizeze tabelele
# din baza de date pe baza claselor tale @Entity. Perfect pentru dezvoltare.
spring.jpa.hibernate.ddl-auto=update

# (Optional) Arata in consola query-urile SQL pe care le execut?
spring.jpa.show-sql=true